kind: pipeline
type: docker
name: Build

workspace:
  path: /app

steps:
- name: deploy
  image: plugins/docker
  settings:
    auto_tag: true
    username:
      from_secret: DOCKER_HUB_USERNAME
    password:
      from_secret: DOCKER_HUB_PASSWORD
    repo: nierot/ibs3
    dockerfile: Dockerfile.drone
- name: notify
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: DISCORD_WEBHOOK_ID
    webhook_token:
      from_secret: DISCORD_WEBHOOK_TOKEN
    message: "{{#success build.status}}✅{{else}}❌{{/success}}  Repository `[{{repo.name}}/{{commit.branch}}]` triggered by event `[{{uppercase build.event}}]` for build.\n    - Commit [[{{commit.sha}}]({{commit.link}})]\n    - Author `[{{commit.author}} / {{commit.email}}]`\n    - Message: {{commit.message}}    - Drone build [[#{{build.number}}]({{build.link}})] reported `[{{uppercase build.status}}]` at `[{{datetime build.finished \"2006.01.02 15:04\" \"\"}}]`\n​"
    username: Miel Monteur
  when:
    status: [ success, failure, changed ]

trigger:
  branch:
  - drone
  # ref:
  # - refs/tags/*