kind: pipeline
type: docker
name: Build

workspace:
  path: /app

steps:
- name: deploy
  image: plugins/docker
  settings:
    auto_tag: true
    username:
      from_secret: DOCKER_HUB_USERNAME
    password:
      from_secret: DOCKER_HUB_PASSWORD
    repo: nierot/ibs3
    dockerfile: Dockerfile.drone
- name: notify
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: DISCORD_WEBHOOK_ID
    webhook_token:
      from_secret: DISCORD_WEBHOOK_TOKEN
    message: "{{#success build.status}}🎉 IBS build is geslaagd! {{else}}👎 IBS build is stukkie wukkie 😢{{/success}}\nRepo `[{{repo.name}}/{{commit.branch}}]` getriggerd door `[{{uppercase build.event}}]`.\n- Commit `[[{{commit.sha}}]({{commit.link}})]`\n- Door `[{{commit.author}} / {{commit.email}}]`\n- Onzin berichtje: {{commit.message}}\n- Drone build [[#{{build.number}}]({{build.link}})] heeft als status `[{{uppercase build.status}}]` om `[{{datetime build.finished \"2006.01.02 15:04\" \"\"}}]`\n"​
    username: Miel Monteur
  when:
    status: [ success, failure, changed ]

trigger:
  branch:
  - drone
  # ref:
  # - refs/tags/*