kind: pipeline
type: docker
name: Build

workspace:
  path: /app

steps:
- name: deploy
  image: plugins/docker
  settings:
    auto_tag: true
    username:
      from_secret: DOCKER_HUB_USERNAME
    password:
      from_secret: DOCKER_HUB_PASSWORD
    repo: nierot/ibs3
    dockerfile: Dockerfile.drone
- name: notify
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: DISCORD_WEBHOOK_ID
    webhook_token:
      from_secret: DISCORD_WEBHOOK_TOKEN
    message: >
      {{#success build.status}}Huts! IBS build is geslaagd!{{else}}Sip, de build is gefaald {{/success}}\n
      Commit: [[{{commit.sha}}]({{commit.link}})]\n
      Door: [{{commit.author}} / {{commit.email}}]\n
      Bericht: {{commit.message}}\n
      Build: [[#{{build.number}}]({{build.link}})]
    username: Miel Monteur
  when:
    status: [ success, failure, changed ]

trigger:
  branch:
  - drone
  # ref:
  # - refs/tags/*