kind: pipeline
type: docker
name: Build

workspace:
  path: /app

steps:
- name: deploy
  image: plugins/docker
  when:
    branch:
    - drone
    ref:
    - refs/tags/*
  tags:
  - ${}
  settings:
    username:
      from_secret: DOCKER_HUB_USERNAME
    password:
      from_secret: DOCKER_HUB_PASSWORD
    repo: nierot/ibs3
    dockerfile: Dockerfile.drone
- name: notify
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: DISCORD_WEBHOOK_ID
    webhook_token:
      from_secret: DISCORD_WEBHOOK_TOKEN
  when:
    status:
    - success
    - failure

--
kind: pipeline
type: docker
name: Promote

workspace:
  path: /app

steps:
